// Comprehensive job titles for autocomplete
export const commonJobTitles = [
  // Tech & IT Roles
  { value: 'software-engineer', label: 'Software Engineer' },
  { value: 'senior-software-engineer', label: 'Senior Software Engineer' },
  { value: 'frontend-developer', label: 'Frontend Developer' },
  { value: 'backend-developer', label: 'Backend Developer' },
  { value: 'full-stack-developer', label: 'Full Stack Developer' },
  { value: 'mobile-app-developer', label: 'Mobile App Developer' },
  { value: 'react-developer', label: 'React Developer' },
  { value: 'android-developer', label: 'Android Developer' },
  { value: 'ios-developer', label: 'iOS Developer' },
  { value: 'web-developer', label: 'Web Developer' },
  { value: 'ui-ux-designer', label: 'UI/UX Designer' },
  { value: 'product-designer', label: 'Product Designer' },
  { value: 'system-administrator', label: 'System Administrator' },
  { value: 'database-administrator', label: 'Database Administrator' },
  { value: 'network-engineer', label: 'Network Engineer' },
  { value: 'cybersecurity-analyst', label: 'Cybersecurity Analyst' },
  { value: 'devops-engineer', label: 'DevOps Engineer' },
  { value: 'cloud-architect', label: 'Cloud Architect' },
  { value: 'data-engineer', label: 'Data Engineer' },
  { value: 'data-analyst', label: 'Data Analyst' },
  { value: 'data-scientist', label: 'Data Scientist' },
  { value: 'machine-learning-engineer', label: 'Machine Learning Engineer' },
  { value: 'ai-researcher', label: 'AI Researcher' },
  { value: 'qa-engineer', label: 'QA Engineer' },
  { value: 'technical-support-specialist', label: 'Technical Support Specialist' },
  { value: 'it-manager', label: 'IT Manager' },
  { value: 'cto', label: 'Chief Technology Officer (CTO)' },
  { value: 'cio', label: 'Chief Information Officer (CIO)' },
  
  // Business & Management
  { value: 'ceo', label: 'Chief Executive Officer (CEO)' },
  { value: 'cfo', label: 'Chief Financial Officer (CFO)' },
  { value: 'coo', label: 'Chief Operating Officer (COO)' },
  { value: 'chief-marketing-officer', label: 'Chief Marketing Officer (CMO)' },
  { value: 'business-analyst', label: 'Business Analyst' },
  { value: 'product-manager', label: 'Product Manager' },
  { value: 'project-manager', label: 'Project Manager' },
  { value: 'operations-manager', label: 'Operations Manager' },
  { value: 'business-development-manager', label: 'Business Development Manager' },
  { value: 'account-manager', label: 'Account Manager' },
  { value: 'sales-manager', label: 'Sales Manager' },
  { value: 'sales-representative', label: 'Sales Representative' },
  { value: 'marketing-manager', label: 'Marketing Manager' },
  { value: 'digital-marketing-specialist', label: 'Digital Marketing Specialist' },
  { value: 'social-media-manager', label: 'Social Media Manager' },
  { value: 'human-resources-manager', label: 'Human Resources Manager' },
  { value: 'hr-specialist', label: 'HR Specialist' },
  { value: 'recruiter', label: 'Recruiter' },
  { value: 'administrative-assistant', label: 'Administrative Assistant' },
  { value: 'executive-assistant', label: 'Executive Assistant' },
  { value: 'office-manager', label: 'Office Manager' },
  
  // Finance & Accounting
  { value: 'accountant', label: 'Accountant' },
  { value: 'senior-accountant', label: 'Senior Accountant' },
  { value: 'financial-analyst', label: 'Financial Analyst' },
  { value: 'financial-advisor', label: 'Financial Advisor' },
  { value: 'investment-banker', label: 'Investment Banker' },
  { value: 'tax-consultant', label: 'Tax Consultant' },
  { value: 'auditor', label: 'Auditor' },
  { value: 'bookkeeper', label: 'Bookkeeper' },
  { value: 'financial-controller', label: 'Financial Controller' },
  { value: 'finance-manager', label: 'Finance Manager' },
  { value: 'bank-teller', label: 'Bank Teller' },
  { value: 'bank-manager', label: 'Bank Manager' },
  { value: 'loan-officer', label: 'Loan Officer' },
  { value: 'credit-analyst', label: 'Credit Analyst' },

  // Healthcare
  { value: 'doctor', label: 'Doctor' },
  { value: 'physician', label: 'Physician' },
  { value: 'nurse', label: 'Nurse' },
  { value: 'registered-nurse', label: 'Registered Nurse' },
  { value: 'nurse-practitioner', label: 'Nurse Practitioner' },
  { value: 'pharmacist', label: 'Pharmacist' },
  { value: 'dentist', label: 'Dentist' },
  { value: 'physical-therapist', label: 'Physical Therapist' },
  { value: 'occupational-therapist', label: 'Occupational Therapist' },
  { value: 'medical-technician', label: 'Medical Technician' },
  { value: 'laboratory-technician', label: 'Laboratory Technician' },
  { value: 'radiologist', label: 'Radiologist' },
  { value: 'surgeon', label: 'Surgeon' },
  { value: 'nutritionist', label: 'Nutritionist' },
  { value: 'dietitian', label: 'Dietitian' },
  { value: 'healthcare-administrator', label: 'Healthcare Administrator' },
  { value: 'medical-assistant', label: 'Medical Assistant' },
  { value: 'paramedic', label: 'Paramedic' },
  
  // Education
  { value: 'teacher', label: 'Teacher' },
  { value: 'professor', label: 'Professor' },
  { value: 'lecturer', label: 'Lecturer' },
  { value: 'assistant-professor', label: 'Assistant Professor' },
  { value: 'school-principal', label: 'School Principal' },
  { value: 'educational-consultant', label: 'Educational Consultant' },
  { value: 'tutor', label: 'Tutor' },
  { value: 'school-counselor', label: 'School Counselor' },
  { value: 'assistant-teacher', label: 'Assistant Teacher' },
  { value: 'librarian', label: 'Librarian' },
  { value: 'curriculum-developer', label: 'Curriculum Developer' },
  
  // Engineering & Construction
  { value: 'architect', label: 'Architect' },
  { value: 'civil-engineer', label: 'Civil Engineer' },
  { value: 'electrical-engineer', label: 'Electrical Engineer' },
  { value: 'mechanical-engineer', label: 'Mechanical Engineer' },
  { value: 'chemical-engineer', label: 'Chemical Engineer' },
  { value: 'structural-engineer', label: 'Structural Engineer' },
  { value: 'construction-manager', label: 'Construction Manager' },
  { value: 'project-engineer', label: 'Project Engineer' },
  { value: 'surveyor', label: 'Surveyor' },
  { value: 'cad-technician', label: 'CAD Technician' },
  { value: 'drafter', label: 'Drafter' },

  // Creative & Design
  { value: 'graphic-designer', label: 'Graphic Designer' },
  { value: 'art-director', label: 'Art Director' },
  { value: 'creative-director', label: 'Creative Director' },
  { value: 'interior-designer', label: 'Interior Designer' },
  { value: 'photographer', label: 'Photographer' },
  { value: 'videographer', label: 'Videographer' },
  { value: 'content-creator', label: 'Content Creator' },
  { value: 'content-writer', label: 'Content Writer' },
  { value: 'copywriter', label: 'Copywriter' },
  { value: 'editor', label: 'Editor' },
  { value: 'journalist', label: 'Journalist' },
  { value: 'animator', label: 'Animator' },
  { value: 'illustrator', label: 'Illustrator' },
  { value: 'ux-writer', label: 'UX Writer' },
  
  // Service & Hospitality
  { value: 'customer-service-representative', label: 'Customer Service Representative' },
  { value: 'customer-support-specialist', label: 'Customer Support Specialist' },
  { value: 'receptionist', label: 'Receptionist' },
  { value: 'hotel-manager', label: 'Hotel Manager' },
  { value: 'event-planner', label: 'Event Planner' },
  { value: 'restaurant-manager', label: 'Restaurant Manager' },
  { value: 'chef', label: 'Chef' },
  { value: 'head-chef', label: 'Head Chef' },
  { value: 'waiter', label: 'Waiter/Waitress' },
  { value: 'barista', label: 'Barista' },
  { value: 'flight-attendant', label: 'Flight Attendant' },
  { value: 'tour-guide', label: 'Tour Guide' },
  { value: 'travel-agent', label: 'Travel Agent' },
  
  // Legal
  { value: 'attorney', label: 'Attorney' },
  { value: 'lawyer', label: 'Lawyer' },
  { value: 'legal-assistant', label: 'Legal Assistant' },
  { value: 'paralegal', label: 'Paralegal' },
  { value: 'judge', label: 'Judge' },
  { value: 'compliance-officer', label: 'Compliance Officer' },
  { value: 'legal-consultant', label: 'Legal Consultant' },
  
  // Scientific
  { value: 'researcher', label: 'Researcher' },
  { value: 'scientist', label: 'Scientist' },
  { value: 'biologist', label: 'Biologist' },
  { value: 'chemist', label: 'Chemist' },
  { value: 'physicist', label: 'Physicist' },
  { value: 'environmental-scientist', label: 'Environmental Scientist' },
  { value: 'lab-technician', label: 'Lab Technician' },

  // Miscellaneous
  { value: 'consultant', label: 'Consultant' },
  { value: 'freelancer', label: 'Freelancer' },
  { value: 'director', label: 'Director' },
  { value: 'specialist', label: 'Specialist' },
  { value: 'manager', label: 'Manager' },
  { value: 'analyst', label: 'Analyst' },
  { value: 'coordinator', label: 'Coordinator' },
  { value: 'supervisor', label: 'Supervisor' },
  { value: 'administrator', label: 'Administrator' },
  { value: 'assistant', label: 'Assistant' },
  
  // Additional job titles
  { value: 'hr-manager', label: 'HR Manager' },
  { value: 'human-resources-specialist', label: 'Human Resources Specialist' },
  { value: 'information-technology-manager', label: 'Information Technology Manager' },
  { value: 'marketing-coordinator', label: 'Marketing Coordinator' },
  { value: 'marketing-director', label: 'Marketing Director' },
  { value: 'office-assistant', label: 'Office Assistant' },
  { value: 'project-coordinator', label: 'Project Coordinator' },
  { value: 'public-relations-specialist', label: 'Public Relations Specialist' },
  { value: 'quality-assurance-analyst', label: 'Quality Assurance Analyst' },
  { value: 'research-assistant', label: 'Research Assistant' },
  { value: 'sales-associate', label: 'Sales Associate' },
  { value: 'school-teacher', label: 'School Teacher' },
  { value: 'secretary', label: 'Secretary' },
  { value: 'security-officer', label: 'Security Officer' },
  { value: 'software-developer', label: 'Software Developer' },
  { value: 'systems-administrator', label: 'Systems Administrator' },
  { value: 'ux-designer', label: 'UX Designer' },
  { value: 'veterinarian', label: 'Veterinarian' },
  { value: 'web-designer', label: 'Web Designer' }
];

// Common universities in East Africa and globally
export const commonUniversities = [
  { value: 'university-of-dar-es-salaam', label: 'University of Dar es Salaam' },
  { value: 'sokoine-university-of-agriculture', label: 'Sokoine University of Agriculture' },
  { value: 'open-university-of-tanzania', label: 'Open University of Tanzania' },
  { value: 'university-of-dodoma', label: 'University of Dodoma' },
  { value: 'mzumbe-university', label: 'Mzumbe University' },
  { value: 'ardhi-university', label: 'Ardhi University' },
  { value: 'muhimbili-university-of-health-and-allied-sciences', label: 'Muhimbili University of Health and Allied Sciences' },
  { value: 'moshi-co-operative-university', label: 'Moshi Co-operative University' },
  { value: 'state-university-of-zanzibar', label: 'State University of Zanzibar' },
  { value: 'makerere-university', label: 'Makerere University' },
  { value: 'university-of-nairobi', label: 'University of Nairobi' },
  { value: 'kenyatta-university', label: 'Kenyatta University' },
  { value: 'strathmore-university', label: 'Strathmore University' },
  { value: 'moi-university', label: 'Moi University' },
  { value: 'jomo-kenyatta-university-of-agriculture-and-technology', label: 'Jomo Kenyatta University of Agriculture and Technology' },
  { value: 'university-of-rwanda', label: 'University of Rwanda' },
  { value: 'mount-kenya-university', label: 'Mount Kenya University' },
  { value: 'catholic-university-of-eastern-africa', label: 'Catholic University of Eastern Africa' },
  { value: 'addis-ababa-university', label: 'Addis Ababa University' },
  { value: 'university-of-oxford', label: 'University of Oxford' },
  { value: 'harvard-university', label: 'Harvard University' },
  { value: 'stanford-university', label: 'Stanford University' },
  { value: 'massachusetts-institute-of-technology', label: 'Massachusetts Institute of Technology' },
  { value: 'university-of-cambridge', label: 'University of Cambridge' },
  { value: 'yale-university', label: 'Yale University' },
  { value: 'university-of-toronto', label: 'University of Toronto' },
  { value: 'university-of-cape-town', label: 'University of Cape Town' },
  { value: 'university-of-witwatersrand', label: 'University of Witwatersrand' },
  { value: 'cairo-university', label: 'Cairo University' }
];

// Common cities in Tanzania and East Africa
export const commonLocations = [
  { value: 'dar-es-salaam', label: 'Dar es Salaam, Tanzania' },
  { value: 'arusha', label: 'Arusha, Tanzania' },
  { value: 'mwanza', label: 'Mwanza, Tanzania' },
  { value: 'tanga', label: 'Tanga, Tanzania' },
  { value: 'dodoma', label: 'Dodoma, Tanzania' },
  { value: 'mbeya', label: 'Mbeya, Tanzania' },
  { value: 'morogoro', label: 'Morogoro, Tanzania' },
  { value: 'zanzibar', label: 'Zanzibar, Tanzania' },
  { value: 'kigoma', label: 'Kigoma, Tanzania' },
  { value: 'nairobi', label: 'Nairobi, Kenya' },
  { value: 'mombasa', label: 'Mombasa, Kenya' },
  { value: 'nakuru', label: 'Nakuru, Kenya' },
  { value: 'kisumu', label: 'Kisumu, Kenya' },
  { value: 'kampala', label: 'Kampala, Uganda' },
  { value: 'entebbe', label: 'Entebbe, Uganda' },
  { value: 'jinja', label: 'Jinja, Uganda' },
  { value: 'kigali', label: 'Kigali, Rwanda' },
  { value: 'bujumbura', label: 'Bujumbura, Burundi' },
  { value: 'addis-ababa', label: 'Addis Ababa, Ethiopia' },
  { value: 'johannesburg', label: 'Johannesburg, South Africa' },
  { value: 'cape-town', label: 'Cape Town, South Africa' },
  { value: 'cairo', label: 'Cairo, Egypt' },
  { value: 'lagos', label: 'Lagos, Nigeria' },
  { value: 'accra', label: 'Accra, Ghana' }
];

// Common skills for various professions
export const commonSkills = [
  { value: 'microsoft-office', label: 'Microsoft Office Suite' },
  { value: 'excel', label: 'Microsoft Excel' },
  { value: 'word', label: 'Microsoft Word' },
  { value: 'powerpoint', label: 'Microsoft PowerPoint' },
  { value: 'project-management', label: 'Project Management' },
  { value: 'leadership', label: 'Leadership' },
  { value: 'communication', label: 'Communication' },
  { value: 'teamwork', label: 'Teamwork' },
  { value: 'problem-solving', label: 'Problem Solving' },
  { value: 'time-management', label: 'Time Management' },
  { value: 'customer-service', label: 'Customer Service' },
  { value: 'critical-thinking', label: 'Critical Thinking' },
  { value: 'analytical-skills', label: 'Analytical Skills' },
  { value: 'strategic-planning', label: 'Strategic Planning' },
  { value: 'research', label: 'Research' },
  { value: 'data-analysis', label: 'Data Analysis' },
  { value: 'social-media', label: 'Social Media' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'sales', label: 'Sales' },
  { value: 'negotiation', label: 'Negotiation' },
  { value: 'public-speaking', label: 'Public Speaking' },
  { value: 'team-management', label: 'Team Management' },
  { value: 'budgeting', label: 'Budgeting' },
  { value: 'financial-analysis', label: 'Financial Analysis' },
  { value: 'accounting', label: 'Accounting' },
  { value: 'html-css', label: 'HTML/CSS' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'react', label: 'React' },
  { value: 'nodejs', label: 'Node.js' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'sql', label: 'SQL' },
  { value: 'database-management', label: 'Database Management' },
  { value: 'agile', label: 'Agile Methodology' },
  { value: 'scrum', label: 'Scrum' },
  { value: 'graphic-design', label: 'Graphic Design' },
  { value: 'photoshop', label: 'Adobe Photoshop' },
  { value: 'illustrator', label: 'Adobe Illustrator' },
  { value: 'ui-design', label: 'UI Design' },
  { value: 'ux-design', label: 'UX Design' },
  { value: 'content-writing', label: 'Content Writing' },
  { value: 'copywriting', label: 'Copywriting' },
  { value: 'seo', label: 'SEO' },
  { value: 'digital-marketing', label: 'Digital Marketing' }
];
