// Common job titles for autocomplete
export const commonJobTitles = [
  { value: 'accountant', label: 'Accountant' },
  { value: 'account-manager', label: 'Account Manager' },
  { value: 'administrative-assistant', label: 'Administrative Assistant' },
  { value: 'architect', label: 'Architect' },
  { value: 'art-director', label: 'Art Director' },
  { value: 'assistant-teacher', label: 'Assistant Teacher' },
  { value: 'bank-teller', label: 'Bank Teller' },
  { value: 'business-analyst', label: 'Business Analyst' },
  { value: 'business-development-manager', label: 'Business Development Manager' },
  { value: 'ceo', label: 'Chief Executive Officer (CEO)' },
  { value: 'cfo', label: 'Chief Financial Officer (CFO)' },
  { value: 'cio', label: 'Chief Information Officer (CIO)' },
  { value: 'civil-engineer', label: 'Civil Engineer' },
  { value: 'content-writer', label: 'Content Writer' },
  { value: 'customer-service-representative', label: 'Customer Service Representative' },
  { value: 'data-analyst', label: 'Data Analyst' },
  { value: 'data-scientist', label: 'Data Scientist' },
  { value: 'dentist', label: 'Dentist' },
  { value: 'designer', label: 'Designer' },
  { value: 'developer', label: 'Developer' },
  { value: 'director', label: 'Director' },
  { value: 'doctor', label: 'Doctor' },
  { value: 'editor', label: 'Editor' },
  { value: 'electrical-engineer', label: 'Electrical Engineer' },
  { value: 'executive-assistant', label: 'Executive Assistant' },
  { value: 'financial-advisor', label: 'Financial Advisor' },
  { value: 'financial-analyst', label: 'Financial Analyst' },
  { value: 'front-desk-clerk', label: 'Front Desk Clerk' },
  { value: 'front-end-developer', label: 'Front End Developer' },
  { value: 'full-stack-developer', label: 'Full Stack Developer' },
  { value: 'graphic-designer', label: 'Graphic Designer' },
  { value: 'hr-manager', label: 'HR Manager' },
  { value: 'human-resources-specialist', label: 'Human Resources Specialist' },
  { value: 'information-technology-manager', label: 'Information Technology Manager' },
  { value: 'lawyer', label: 'Lawyer' },
  { value: 'legal-assistant', label: 'Legal Assistant' },
  { value: 'marketing-coordinator', label: 'Marketing Coordinator' },
  { value: 'marketing-director', label: 'Marketing Director' },
  { value: 'marketing-manager', label: 'Marketing Manager' },
  { value: 'mechanical-engineer', label: 'Mechanical Engineer' },
  { value: 'medical-assistant', label: 'Medical Assistant' },
  { value: 'nurse', label: 'Nurse' },
  { value: 'office-assistant', label: 'Office Assistant' },
  { value: 'office-manager', label: 'Office Manager' },
  { value: 'operations-manager', label: 'Operations Manager' },
  { value: 'pharmacist', label: 'Pharmacist' },
  { value: 'photographer', label: 'Photographer' },
  { value: 'physician', label: 'Physician' },
  { value: 'product-manager', label: 'Product Manager' },
  { value: 'project-coordinator', label: 'Project Coordinator' },
  { value: 'project-manager', label: 'Project Manager' },
  { value: 'public-relations-specialist', label: 'Public Relations Specialist' },
  { value: 'quality-assurance-analyst', label: 'Quality Assurance Analyst' },
  { value: 'receptionist', label: 'Receptionist' },
  { value: 'registered-nurse', label: 'Registered Nurse' },
  { value: 'research-assistant', label: 'Research Assistant' },
  { value: 'sales-associate', label: 'Sales Associate' },
  { value: 'sales-manager', label: 'Sales Manager' },
  { value: 'sales-representative', label: 'Sales Representative' },
  { value: 'school-teacher', label: 'School Teacher' },
  { value: 'secretary', label: 'Secretary' },
  { value: 'security-officer', label: 'Security Officer' },
  { value: 'social-media-manager', label: 'Social Media Manager' },
  { value: 'software-developer', label: 'Software Developer' },
  { value: 'software-engineer', label: 'Software Engineer' },
  { value: 'systems-administrator', label: 'Systems Administrator' },
  { value: 'teacher', label: 'Teacher' },
  { value: 'ux-designer', label: 'UX Designer' },
  { value: 'veterinarian', label: 'Veterinarian' },
  { value: 'web-designer', label: 'Web Designer' },
  { value: 'web-developer', label: 'Web Developer' },
];

// Common universities in East Africa and globally
export const commonUniversities = [
  { value: 'university-of-dar-es-salaam', label: 'University of Dar es Salaam' },
  { value: 'sokoine-university-of-agriculture', label: 'Sokoine University of Agriculture' },
  { value: 'open-university-of-tanzania', label: 'Open University of Tanzania' },
  { value: 'university-of-dodoma', label: 'University of Dodoma' },
  { value: 'mzumbe-university', label: 'Mzumbe University' },
  { value: 'ardhi-university', label: 'Ardhi University' },
  { value: 'muhimbili-university-of-health-and-allied-sciences', label: 'Muhimbili University of Health and Allied Sciences' },
  { value: 'moshi-co-operative-university', label: 'Moshi Co-operative University' },
  { value: 'state-university-of-zanzibar', label: 'State University of Zanzibar' },
  { value: 'makerere-university', label: 'Makerere University' },
  { value: 'university-of-nairobi', label: 'University of Nairobi' },
  { value: 'kenyatta-university', label: 'Kenyatta University' },
  { value: 'strathmore-university', label: 'Strathmore University' },
  { value: 'moi-university', label: 'Moi University' },
  { value: 'jomo-kenyatta-university-of-agriculture-and-technology', label: 'Jomo Kenyatta University of Agriculture and Technology' },
  { value: 'university-of-rwanda', label: 'University of Rwanda' },
  { value: 'mount-kenya-university', label: 'Mount Kenya University' },
  { value: 'catholic-university-of-eastern-africa', label: 'Catholic University of Eastern Africa' },
  { value: 'addis-ababa-university', label: 'Addis Ababa University' },
  { value: 'university-of-oxford', label: 'University of Oxford' },
  { value: 'harvard-university', label: 'Harvard University' },
  { value: 'stanford-university', label: 'Stanford University' },
  { value: 'massachusetts-institute-of-technology', label: 'Massachusetts Institute of Technology' },
  { value: 'university-of-cambridge', label: 'University of Cambridge' },
  { value: 'yale-university', label: 'Yale University' },
  { value: 'university-of-toronto', label: 'University of Toronto' },
  { value: 'university-of-cape-town', label: 'University of Cape Town' },
  { value: 'university-of-witwatersrand', label: 'University of Witwatersrand' },
  { value: 'cairo-university', label: 'Cairo University' },
];

// Common cities in Tanzania and East Africa
export const commonLocations = [
  { value: 'dar-es-salaam', label: 'Dar es Salaam, Tanzania' },
  { value: 'arusha', label: 'Arusha, Tanzania' },
  { value: 'mwanza', label: 'Mwanza, Tanzania' },
  { value: 'tanga', label: 'Tanga, Tanzania' },
  { value: 'dodoma', label: 'Dodoma, Tanzania' },
  { value: 'mbeya', label: 'Mbeya, Tanzania' },
  { value: 'morogoro', label: 'Morogoro, Tanzania' },
  { value: 'zanzibar', label: 'Zanzibar, Tanzania' },
  { value: 'kigoma', label: 'Kigoma, Tanzania' },
  { value: 'nairobi', label: 'Nairobi, Kenya' },
  { value: 'mombasa', label: 'Mombasa, Kenya' },
  { value: 'nakuru', label: 'Nakuru, Kenya' },
  { value: 'kisumu', label: 'Kisumu, Kenya' },
  { value: 'kampala', label: 'Kampala, Uganda' },
  { value: 'entebbe', label: 'Entebbe, Uganda' },
  { value: 'jinja', label: 'Jinja, Uganda' },
  { value: 'kigali', label: 'Kigali, Rwanda' },
  { value: 'bujumbura', label: 'Bujumbura, Burundi' },
  { value: 'addis-ababa', label: 'Addis Ababa, Ethiopia' },
  { value: 'johannesburg', label: 'Johannesburg, South Africa' },
  { value: 'cape-town', label: 'Cape Town, South Africa' },
  { value: 'cairo', label: 'Cairo, Egypt' },
  { value: 'lagos', label: 'Lagos, Nigeria' },
  { value: 'accra', label: 'Accra, Ghana' },
];

// Common skills for various professions
export const commonSkills = [
  { value: 'microsoft-office', label: 'Microsoft Office Suite' },
  { value: 'excel', label: 'Microsoft Excel' },
  { value: 'word', label: 'Microsoft Word' },
  { value: 'powerpoint', label: 'Microsoft PowerPoint' },
  { value: 'project-management', label: 'Project Management' },
  { value: 'leadership', label: 'Leadership' },
  { value: 'communication', label: 'Communication' },
  { value: 'teamwork', label: 'Teamwork' },
  { value: 'problem-solving', label: 'Problem Solving' },
  { value: 'time-management', label: 'Time Management' },
  { value: 'customer-service', label: 'Customer Service' },
  { value: 'critical-thinking', label: 'Critical Thinking' },
  { value: 'analytical-skills', label: 'Analytical Skills' },
  { value: 'writing', label: 'Writing' },
  { value: 'public-speaking', label: 'Public Speaking' },
  { value: 'research', label: 'Research' },
  { value: 'data-analysis', label: 'Data Analysis' },
  { value: 'social-media', label: 'Social Media' },
  { value: 'digital-marketing', label: 'Digital Marketing' },
  { value: 'content-creation', label: 'Content Creation' },
  { value: 'seo', label: 'SEO' },
  { value: 'accounting', label: 'Accounting' },
  { value: 'budgeting', label: 'Budgeting' },
  { value: 'sales', label: 'Sales' },
  { value: 'negotiation', label: 'Negotiation' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'react', label: 'React' },
  { value: 'node-js', label: 'Node.js' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'sql', label: 'SQL' },
  { value: 'database-management', label: 'Database Management' },
  { value: 'ui-ux-design', label: 'UI/UX Design' },
  { value: 'adobe-photoshop', label: 'Adobe Photoshop' },
  { value: 'adobe-illustrator', label: 'Adobe Illustrator' },
  { value: 'adobe-indesign', label: 'Adobe InDesign' },
  { value: 'figma', label: 'Figma' },
  { value: 'language-swahili', label: 'Swahili Language' },
  { value: 'language-english', label: 'English Language' },
  { value: 'language-french', label: 'French Language' },
];