// Tanzania regions for autocomplete
export const tanzaniaRegions = [
  { value: 'arusha', label: 'Arusha, Tanzania' },
  { value: 'dar-es-salaam', label: 'Dar es Salaam, Tanzania' },
  { value: 'dodoma', label: 'Dodoma, Tanzania' },
  { value: 'geita', label: 'Geita, Tanzania' },
  { value: 'iringa', label: 'Iringa, Tanzania' },
  { value: 'kagera', label: 'Kagera, Tanzania' },
  { value: 'katavi', label: 'Katavi, Tanzania' },
  { value: 'kigoma', label: 'Kigoma, Tanzania' },
  { value: 'kilimanjaro', label: 'Kilimanjaro, Tanzania' },
  { value: 'lindi', label: 'Lindi, Tanzania' },
  { value: 'manyara', label: 'Manyara, Tanzania' },
  { value: 'mara', label: 'Mara, Tanzania' },
  { value: 'mbeya', label: 'Mbeya, Tanzania' },
  { value: 'morogoro', label: 'Morogoro, Tanzania' },
  { value: 'mtwara', label: 'Mtwara, Tanzania' },
  { value: 'mwanza', label: 'Mwanza, Tanzania' },
  { value: 'njombe', label: 'Njombe, Tanzania' },
  { value: 'pemba-north', label: 'Pemba North, Tanzania' },
  { value: 'pemba-south', label: 'Pemba South, Tanzania' },
  { value: 'pwani', label: 'Pwani, Tanzania' },
  { value: 'rukwa', label: 'Rukwa, Tanzania' },
  { value: 'ruvuma', label: 'Ruvuma, Tanzania' },
  { value: 'shinyanga', label: 'Shinyanga, Tanzania' },
  { value: 'simiyu', label: 'Simiyu, Tanzania' },
  { value: 'singida', label: 'Singida, Tanzania' },
  { value: 'songwe', label: 'Songwe, Tanzania' },
  { value: 'tabora', label: 'Tabora, Tanzania' },
  { value: 'tanga', label: 'Tanga, Tanzania' },
  { value: 'unguja-north', label: 'Unguja North, Tanzania' },
  { value: 'unguja-south', label: 'Unguja South, Tanzania' },
  { value: 'zanzibar-urban', label: 'Zanzibar Urban, Tanzania' },
  { value: 'zanzibar-west', label: 'Zanzibar West, Tanzania' }
];