export const tanzaniaUniversities = [
  "University of Dar es Salaam (UDSM)",
  "Sokoine University of Agriculture (SUA)",
  "Open University of Tanzania (OUT)",
  "State University of Zanzibar (SUZA)",
  "Mzumbe University (MU)",
  "Nelson Mandela African Institution of Science and Technology (NM-AIST)",
  "Muhimbili University of Health and Allied Sciences (MUHAS)",
  "Ardhi University (ARU)",
  "University of Dodoma (UDOM)",
  "Mbeya University of Science and Technology (MUST)",
  "Moshi Cooperative University (MoCU)",
  "Mwalimu Julius K. Nyerere University of Agriculture and Technology (MJNUAT)",
  "Kairuki University (KU)",
  "Abdulrahman Al-Sumait University (SUMAIT)",
  "St. Augustine University of Tanzania (SAUT)",
  "Zanzibar University (ZU)",
  "Tumaini University Makumira (TUMA)",
  "Aga Khan University (AKU)",
  "Catholic University of Health and Allied Sciences (CUHAS)",
  "University of Arusha (UoA)",
  "St. Joseph University in Tanzania (SJUIT)",
  "Teofilo Kisanji University (TEKU)",
  "Mwenge Catholic University (MWECAU)",
  "Muslim University of Morogoro (MUM)",
  "University of Iringa (UoI)",
  "St. John's University of Tanzania (SJUT)",
  "Kampala International University in Tanzania (KIUT)",
  "United African University of Tanzania (UAUT)",
  "Ruaha Catholic University (RUCU)",
  "Mwanza University (MzU)",
  "Catholic University of Mbeya (CUoM)",
  "Dar es Salaam Tumaini University (DarTU)",
  "Rabininsia Memorial University of Health and Allied Sciences (RMUHAS)",
  "University of Medical Sciences and Technology (UMST)",
  "Islamic University of East Africa (IUEA)",
  "KCMC University"
];