import type { CVData } from '@/types/cv';

export const sampleCVData: CVData = {
  personalInfo: {
    firstName: 'Noela',
    lastName: 'Bwemero',
    email: 'noela.bwemero@lexchambers.co.tz',
    phone: '+255 754 892 341',
    location: 'Dar es Salaam, Tanzania',
    professionalTitle: 'Senior Corporate Lawyer',
    linkedin: 'linkedin.com/in/noelabwemero',
    website: 'www.noelabwemero.com',
    photoUrl: 'https://drive.google.com/uc?export=view&id=1W8Q9AQUlxD7caDS0dQQR-4HaCjjCpjso',
  },
  summary: 'Accomplished Senior Corporate Lawyer with 8+ years of experience specializing in commercial law, mergers & acquisitions, and corporate governance across East Africa. Successfully closed over TZS 50 billion in M&A transactions and advised Fortune 500 companies on market entry strategies. Known for meticulous contract drafting, strategic negotiation skills, and deep understanding of Tanzanian regulatory frameworks. Admitted to the Tanganyika Law Society and certified mediator.',
  workExperiences: [
    {
      id: '1',
      jobTitle: 'Senior Corporate Lawyer',
      company: 'Mkono & Co. Advocates',
      location: 'Dar es Salaam, Tanzania',
      startDate: 'March 2022',
      endDate: '',
      isCurrent: true,
      achievements: [
        'Lead counsel on TZS 28 billion acquisition of Tanzanian fintech startup by international payment processor',
        'Advise multinational corporations including Vodacom, TotalEnergies, and Barrick Gold on corporate restructuring',
        'Drafted and negotiated 150+ commercial contracts including joint ventures and shareholder agreements',
        'Mentor team of 4 junior associates, conducting weekly training sessions on corporate law best practices',
        'Achieved 95% success rate in commercial arbitration cases before the Tanzania Arbitration Centre',
      ],
    },
    {
      id: '2',
      jobTitle: 'Corporate Legal Counsel',
      company: 'CRDB Bank Plc',
      location: 'Dar es Salaam, Tanzania',
      startDate: 'June 2019',
      endDate: 'February 2022',
      isCurrent: false,
      achievements: [
        'Provided legal support for bank\'s TZS 180 billion corporate lending portfolio',
        'Structured syndicated loan facilities for major infrastructure projects including Dar BRT',
        'Led legal workstream for core banking system migration, negotiating contracts worth TZS 12 billion',
        'Reduced contract turnaround time by 40% through standardized template library',
      ],
    },
    {
      id: '3',
      jobTitle: 'Associate Lawyer',
      company: 'Rex Attorneys',
      location: 'Dar es Salaam, Tanzania',
      startDate: 'September 2016',
      endDate: 'May 2019',
      isCurrent: false,
      achievements: [
        'Handled corporate registrations and regulatory submissions for 80+ client companies',
        'Assisted in landmark TZS 15 billion cross-border acquisition in telecommunications sector',
        'Conducted legal due diligence for private equity investments across multiple sectors',
      ],
    },
  ],
  education: [
    {
      id: '1',
      degree: 'Master of Laws (LL.M)',
      institution: 'University of Cape Town',
      fieldOfStudy: 'International Commercial Law',
      graduationDate: '2020',
    },
    {
      id: '2',
      degree: 'Bachelor of Laws (LL.B)',
      institution: 'University of Dar es Salaam',
      fieldOfStudy: 'Law',
      graduationDate: '2016',
    },
  ],
  skills: [
    { id: '1', name: 'Corporate Law & Governance', level: 'expert' },
    { id: '2', name: 'Mergers & Acquisitions', level: 'expert' },
    { id: '3', name: 'Contract Drafting & Negotiation', level: 'expert' },
    { id: '4', name: 'Legal Due Diligence', level: 'expert' },
    { id: '5', name: 'Commercial Arbitration', level: 'advanced' },
    { id: '6', name: 'Banking & Finance Law', level: 'advanced' },
    { id: '7', name: 'Regulatory Compliance', level: 'advanced' },
    { id: '8', name: 'Employment Law', level: 'intermediate' },
    { id: '9', name: 'Legal Research', level: 'expert' },
    { id: '10', name: 'Client Relationship Management', level: 'expert' },
    { id: '11', name: 'Strategic Negotiation', level: 'expert' },
    { id: '12', name: 'Microsoft Office Suite', level: 'advanced' },
  ],
  languages: [
    { id: '1', name: 'Swahili', proficiency: 'native' },
    { id: '2', name: 'English', proficiency: 'fluent' },
    { id: '3', name: 'French', proficiency: 'conversational' },
  ],
  references: [
    {
      id: '1',
      name: 'Advocate James Mwakasege',
      title: 'Managing Partner',
      company: 'Mkono & Co. Advocates',
      email: 'jmwakasege@mkono.com',
      phone: '+255 222 116 692',
    },
    {
      id: '2',
      name: 'Dr. Grace Kamuzora',
      title: 'General Counsel',
      company: 'CRDB Bank Plc',
      email: 'grace.kamuzora@crdbbank.co.tz',
      phone: '+255 222 117 442',
    },
  ],
};
